#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export EDITOR=vim
export VISUAL=vim

# Use mvim as the rendering engine
alias vim="mvim -v"
alias ssh="TERM=xterm ssh"
alias ev="vim ~/.vimrc"
alias ez="vim ~/.zshrc"
alias sz="source ~/.zshrc"

# Git
eval "$(hub alias -s)"
alias gst="clear;gws"
alias gtday="g log --since=\"12am\" | ack Date: | wc -l"
alias ga="gia"

# rbenv
eval "$(rbenv init - zsh)"

# virtualenvwrapper
export WORKON_HOME=~/venvs
source /usr/local/bin/virtualenvwrapper.sh
unset VIRTUAL_ENV_DISABLE_PROMPT

# go
export GOPATH=$HOME/codez/go
export PATH="$GOPATH/bin:$PATH"

# fzf
# Usage Examples:
# Select files to add to git: g add <CTRL-T>
# Search history and paste to cli: <CTRL-R>
# Fuzzy completion: <any command> **
# https://github.com/junegunn/fzf/wiki/examples
export FZF_DEFAULT_COMMAND='ag --hidden -g ""'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# fe [FUZZY PATTERN] - Open the selected file with the default editor
#   - Bypass fuzzy finder if there's only one match (--select-1)
#   - Exit if there's no match (--exit-0)
function fe() {
  IFS='
'
  local files
  files=($(fzf-tmux --query="$1" --select-1 --exit-0))
  [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
  unset IFS
}
# Modified version where you can press
#   - CTRL-O to open with `open` command,
#   - CTRL-E or Enter key to open with the $EDITOR
function fo() {
  local out file key
  out=$(fzf-tmux --query="$1" --exit-0 --expect=ctrl-o,ctrl-e)
  key=$(head -1 <<< "$out")
  file=$(head -2 <<< "$out" | tail -1)
  if [ -n "$file" ]; then
    [ "$key" = ctrl-o ] && open "$file" || ${EDITOR:-vim} "$file"
  fi
}

# N1
alias nd="/Users/juan/codez/nylas/N1/N1.sh --dev --enable-logging"
alias nt="/Users/juan/codez/nylas/N1/N1.sh --test --enable-logging"
export PATH="/Users/juan/codez/nylas/arcanist/bin:$PATH"
